/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package centech.sdp.gameloft.game.pid;

import java.util.HashMap;

/**
 *
 * @author Administrator
 */
public class GamePIDLegal {
    public static final HashMap<String, String> pidMap = new HashMap();   
    public static String[] arrPIDDefault = new String[] { "1", "49", "1843", "2036", "153", "657", "477" ,"1215", "1656", "1586"};
    
    static {
        pidMap.put("49", "1000 Words");
        pidMap.put("1707", "2012 Real Footbal");
        pidMap.put("1669", "2014 Real Football Mobile Premium");
        pidMap.put("1843", "Real Football");
        pidMap.put("2618", "Real Football");
        pidMap.put("200", "America's Army");
        pidMap.put("77", "Streetball");

        pidMap.put("2062", "2016 Real Football Mobile Premium");
        pidMap.put("505", "Abracadaball");
        pidMap.put("145", "Air Strike 1944");
        pidMap.put("1628", "Alien Quarantine Mobile Premium");
        pidMap.put("2048", "All Star Cricket 2015");
        pidMap.put("1146", "Asphalt 6: Adrenaline");
        pidMap.put("2036", "Asphalt Nitro Mobile Premium");
        pidMap.put("1590", "Assassin's Creed 3 Mobile Premium");
        pidMap.put("1099", "Assassin's Creed Brotherhood");
        pidMap.put("939", "Avalanche Snowboarding");
        pidMap.put("202", "Big Range Hunting");
        pidMap.put("1", "Block Breaker Deluxe");
        pidMap.put("69", "Block Breaker Valentine");
        pidMap.put("153", "Brain Challenge");
        pidMap.put("364", "Brain Challenge 2");
        pidMap.put("1386", "Brain Challenge 4");
        pidMap.put("768", "Bubble Bash 2");
        pidMap.put("1566", "Bubble Bash 3 Mobile Paymium");
        pidMap.put("1565", "Bubble Bash 3 Mobile Premium");
        pidMap.put("1773", "Bubble Bash Mania");
        pidMap.put("1227", "Cannon Rats");
        pidMap.put("1732", "Cars Mobile Premium");
        pidMap.put("657", "Castle of Magic");
        pidMap.put("30", "Cluster Pirate");
        pidMap.put("241", "Common Knowledge Quiz");
        pidMap.put("827", "Cops");
        pidMap.put("248", "Crazy Campus");
        pidMap.put("1707", "Danger Dash Mobile Premium");
        pidMap.put("477", "Date or Ditch");
        pidMap.put("976", "Date or Ditch 2");
        pidMap.put("1228", "Detective Ridley and the Mysterious Enigm");
        pidMap.put("111", "Diamond Rush");
        pidMap.put("456", "Diamond Twister");
        pidMap.put("1215", "Diamond Twister 2");
        pidMap.put("261", "Die Hard 4.0");
        pidMap.put("1657", "Die Hard 5 Mobile");
        pidMap.put("1656", "Dragon Mania Mobile Premium");
        pidMap.put("1396", "Dungeon Hunter 3 Mobile");
        pidMap.put("20", "Earth Invasion");
        pidMap.put("242", "Everyday English Trainer");
        pidMap.put("639", "Far Cry 2");
        pidMap.put("1519", "Fashion Icon Mobile Premium");
        pidMap.put("1539", "Ferrari GT 3: World Track Mobile Premium");
        pidMap.put("694", "Ferrari GT: Evolution");
        pidMap.put("518", "Ferrari World Championship");
        pidMap.put("227", "Football Party");
        pidMap.put("1516", "Gangstar");
        pidMap.put("1516", "Gangstar City Mobile Premium");
        pidMap.put("1317", "Gangstar Rio: City of Saints");
        pidMap.put("1557", "Green Farm 3 Mobile Freemium");
        pidMap.put("1666", "Green Farm 3 Mobile Premium");
        pidMap.put("1679", "GT Racing 2 Mobile Premium");
        pidMap.put("31", "Gulo's Tale");
        pidMap.put("1039", "High School Hook Ups");
        pidMap.put("1750", "Ice Age Village Mobile Premium");
        pidMap.put("2026", "Ice Age: Scrat-Ventures Mobile Premium");
        pidMap.put("1697", "Iron Man 3 Mobile Premium");
        pidMap.put("1652", "Kingdoms and Lords Mobile Premium");
        pidMap.put("476", "KO Fighters 2D + 3D");
        pidMap.put("399", "KO Fighters 3D");
        pidMap.put("403", "Las Vegas Nights");
        pidMap.put("1056", "Let's Go Bowling");
        pidMap.put("744", "Let's Golf");
        pidMap.put("1453", "Little Big City Mobile Premium");
        pidMap.put("1524", "Littlest Pet Shop Mobile Premium");
        pidMap.put("3", "Lock'em Up");
        pidMap.put("918", "Mega Tower Assault");
        pidMap.put("422", "Megacity Empire: New York");
        pidMap.put("1467", "Men in Black 3");
        pidMap.put("831", "Miami Nights 2");
        pidMap.put("127", "Miami Nights: Singles in the City");
        pidMap.put("58", "Midnight Bowling");
        pidMap.put("1586", "Midnight Bowling 3 Mobile Premium");
        pidMap.put("137", "Midnight Bowling 3D");
        pidMap.put("460", "Midnight Darts");
        pidMap.put("2305", "Midnight Pool");
        pidMap.put("1306", "Midnight Pool 3 Paymium/Premium");
        pidMap.put("2305", "Midnight Pool 4 Mobile Premium");
        pidMap.put("268", "Minigolf revolution: Pirate Park");
        pidMap.put("946", "Modern Combat 2: Black Pegasus");
        pidMap.put("1660", "Modern Combat 4 Mobile Premium");
        pidMap.put("1743", "Monsters University Mobile Premium");
        pidMap.put("1268", "Motocross : Trial Extreme");
        pidMap.put("1183", "My Life in New York");
        pidMap.put("82", "Mystery Mansion Pinball");
        pidMap.put("1627", "N.O.V.A. 3 Mobile Premium");
        pidMap.put("1083", "Narnia: The Voyage of the Dawn Treader");
        pidMap.put("150", "Naval Battle Mission Commander");
        pidMap.put("507", "New York Nights 2");
        pidMap.put("57", "New York Nights: Success in the City");
        pidMap.put("1060", "Ninja Prophecy");
        pidMap.put("792", "Nitro Street Racing 2");
        pidMap.put("239", "Pirates of the Seven Seas");
        pidMap.put("29", "Planet Zero");
        pidMap.put("138", "Platinum Kakuro");
        pidMap.put("115", "Platinum Sudoku");
        pidMap.put("741", "Platinum Sudoku 2");
        pidMap.put("557", "Pocket Chef");
        pidMap.put("1058", "Predators");
        pidMap.put("661", "Prince of Persia");
        pidMap.put("1740", "Puzzle Pets Mobile Premium");
        pidMap.put("262", "Rise Of Lost Empires");
        pidMap.put("7", "Siberian Strike");
        pidMap.put("19", "Skate & Slam");
        pidMap.put("1269", "Sonic Advance");
        pidMap.put("813", "Sonic Unleashed");
        pidMap.put("534", "Soul of Darkness");
        pidMap.put("16", "Speed Devils");
        pidMap.put("1763", "Spiderman Ultimate Power Mobile Premium");
        pidMap.put("198", "Spring Break: Cancun goes wild");
        pidMap.put("5", "Summer Volley");
        pidMap.put("1871", "The Amazing Spider-Man 2 Mobile Premium");
        pidMap.put("1527", "The Amazing Spider-Man Mobile Premium");
        pidMap.put("1504", "The Avengers");
        pidMap.put("1542", "The Oregon Trail: American Settler Mobile Premium");
        pidMap.put("1770", "Total Conquest Mobile Premium");
        pidMap.put("79", "Tropical Madness");
        pidMap.put("280", "Turbo Jet Ski 3D");
        pidMap.put("1125", "Vampire Romance");
        pidMap.put("622", "Wild West Guns");
        pidMap.put("1502", "Wonder Zoo Mobile Premium");
        pidMap.put("1282", "Word Crafter");
        pidMap.put("1718", "World At Arms Mobile Premium");
        pidMap.put("721", "Zombie Infection");
        pidMap.put("947", "Zombie Infection 2");
        pidMap.put("1483", "Zombiewood Mobile Premium");
        pidMap.put("103", "Block Breaker Deluxe 2 ");
        pidMap.put("281", "Big Range Hunting 3D");
        pidMap.put("391", "Off-Road Dirt Motocross ");
        pidMap.put("676", "Hero of Sparta");
        pidMap.put("890", "Carnival Land ");
        pidMap.put("903", "Brain Challenge 3 ");
        pidMap.put("986", "Ferrari GT 2: Revolution ");
        pidMap.put("1644", "HANDYGAMES Clouds and Sheep ");
        pidMap.put("1653", "HANDYGAMES Guns and Glory WW2");
        pidMap.put("1686", "HANDYGAMES Tattoo Tycoon");
        pidMap.put("2375", "HANDYGAMES Townsmen");
        pidMap.put("1696", "HANDYGAMES Bulldozer Inc ");
        pidMap.put("1700", "HANDYGAMES Farm Invasion USA ");
        pidMap.put("1887", "BALTORO Bubble Frenzy ");
        pidMap.put("2629", "BALTORO Go Kart Mania 2 ");
        pidMap.put("2518", "BALTORO Catacomb Run");
        pidMap.put("2350", "BALTORO Flappy Duck ");
        pidMap.put("1992", "BALTORO Motocross Mania ");
        pidMap.put("2539", "BALTORO Jet Pack Dash");
        pidMap.put("2057", "BALTORO Ultimate Rally Champions 2");
        pidMap.put("2211", "BALTORO Go Kart Mania PRO");
        pidMap.put("2217", "BALTORO Motorbikes PRO 2015");
        pidMap.put("2224", "BALTORO Freeride Snowboarding");
        pidMap.put("2329", "HANDYGAMES Guns N Glory");
        pidMap.put("2331", "N.O.V.A. Legacy ");
        pidMap.put("2429", "Disney Magic Kingdoms ");
        pidMap.put("2617", "2017 Real Football  ");
        pidMap.put("2721", "Little Big City 2  ");
        pidMap.put("2729", "Sonic Runners Adventure ");
        pidMap.put("2735", "BALTORO Cricket World Trophy 2016");
        pidMap.put("2737", "GLOBALFUN Whac-a-Mole ");
        pidMap.put("2746", "BALTORO World Bowling Tour 2016 ");
        pidMap.put("2756", "HANDYGAMES 1942 Pacific Front ");
        pidMap.put("2764", "GLOBALFUN Great Legends - Robin Hood the Prince");
        pidMap.put("2765", "GLOBALFUN Zoom Bug ");
        pidMap.put("2790", "GLOBALFUN Cristiano Ronaldo 7 Penalty ");
        pidMap.put("2811", "GLOBALFUN Cristiano Ronaldo Football 2016 ");
        pidMap.put("2899", "GLOBALFUN Cannonball 8000 ");
        pidMap.put("2952", "Dungeon Hunter Curse of Heaven ");
        pidMap.put("2983", "GLOBALFUN Monster Blast ");
        pidMap.put("2984", "INLOGIC snakes.io ");
        pidMap.put("2985", "BALTORO Bubble Pop Mania ");
        pidMap.put("2986", "JOYBITS Doodle Creatures ");
        pidMap.put("3257", "JOYBITS Doodle God");
        pidMap.put("2988", "JOYBITS Doodle Farm ");
        pidMap.put("2993", "INLOGIC Pro Tennis 2017 ");
        pidMap.put("2996", "HANDYGAMES Bridge Constructor Medieval ");
        pidMap.put("3029", "ZEPTOLAB Cut the Rope ");
        pidMap.put("3004", "GLOBALFUN Ben 10 Omnitrix Power ");
        pidMap.put("3007", "JOYBITS Jewel Tree: Match It ");
        pidMap.put("3015", "ZEPTOLAB Cut the Rope: Experiments  ");
        pidMap.put("3019", "ZEPTOLAB Pudding Monsters ");
        pidMap.put("3022", "PLAYMOUS Tap the Frog ");
        pidMap.put("3024", "BALTORO Candy Ninja");
        pidMap.put("3030", "BALTORO Super Quad Bikes");
        pidMap.put("3063", "BALTORO Moto Racing Rivals ");
        pidMap.put("3065", "INLOGIC Poke Go ");
        pidMap.put("3081", "BALTORO Cricket World Trophy 2017 ");
        pidMap.put("3090", "2018 Real Football ");
        pidMap.put("3093", "INLOGIC Jewel Ocean");
        pidMap.put("3099", "JOYBITS Doodle Devil ");
        pidMap.put("3100", "INLOGIC Tubby Birds 2");
        pidMap.put("3102", "BALTORO My Breakfast Bar");
        pidMap.put("3108", "HANDYGAMES Dog Hotel - My boarding kennel  ");
        pidMap.put("3110", "HANDYGAMES 1944 Burning Bridges ");
        pidMap.put("3111", "HANDYGAMES Ninja Hero Cats ");
        pidMap.put("3112", "HANDYGAMES Dynamite Fishing - World Games ");
        pidMap.put("3116", "GLOBALFUN Steven Universe - Attack The Light ");
        pidMap.put("3117", "HANDYGAMES Dog World ");
        pidMap.put("3122", "HANDYGAMES Fantasy Baby Animals ");
        pidMap.put("3124", "HANDYGAMES Neoteria");
        pidMap.put("3125", "HANDYGAMES Chess And Mate ");
        pidMap.put("3126", "HANDYGAMES Zombie Blitz ");
        pidMap.put("3128", "INLOGIC Pizza Ninja 4 ");
        pidMap.put("3129", "BALTORO Traffic Racing ");
        pidMap.put("3130", "HANDYGAMES Rocket Island ");
        pidMap.put("3132", "HANDYGAMES Groundskeeper 2");
        pidMap.put("3135", "INLOGIC Moto Rider");
        pidMap.put("3136", "INLOGIC Game of Flows ");
        pidMap.put("3141", "HANDYGAMES Stage Dive Legends");
        pidMap.put("3142", "HANDYGAMES Super Party Sports: Football ");
        pidMap.put("3144", "HANDYGAMES RTL Freestyle Skiing ");
        pidMap.put("3153", "HANDYGAMES Pet World 3D");
        pidMap.put("3184", "HANDYGAMES Gunslugs");
        pidMap.put("3156", "HANDYGAMES Guns'n'Glory Zombies ");
        pidMap.put("3157", "HANDYGAMES Toby the Secret Mine ");
        pidMap.put("3159", "HANDYGAMES 1943 Deadly Desert ");
        pidMap.put("3436", "JOYBITS Real Retro Games ");
        pidMap.put("3175", "BALTORO Candy Flowers Paradise ");
        pidMap.put("3176", "BALTORO 4096 Awesome Blossom ");
        pidMap.put("3177", "BALTORO Go! Fish Go! ");
        pidMap.put("3182", "HANDYGAMES Retro Winter Sports 1986 ");
        pidMap.put("3183", "HANDYGAMES Runes ");
        pidMap.put("3184", "HANDYGAMES Gunslugs 2 ");
        pidMap.put("3185", "HANDYGAMES Heroes of Loot");
        pidMap.put("3186", "HANDYGAMES Space Grunts ");
        pidMap.put("3187", "HANDYGAMES Wild Life - America ");
        pidMap.put("3188", "HANDYGAMES Dream Job Veterinarian ");
        pidMap.put("3189", "HANDYGAMES Dolphins of the Caribbean ");
        pidMap.put("3209", "JOYBITS Ghostanoid ");
        pidMap.put("3210", "GLOBALFUN Generator Rex ");
        pidMap.put("3212", "INLOGIC Drag Racing Pro ");
        pidMap.put("3215", "INLOGIC Dark Assassin ");
        pidMap.put("3216", "GLOBALFUN Zombie Race ");
        pidMap.put("3217", "BALTORO Candy Frenzy ");
        pidMap.put("3218", "BALTORO Awesome Pizza ");
        pidMap.put("3219", "GLOBALFUN Ben 10 Wrath of Psychobos ");
        pidMap.put("3222", "INLOGIC Bubble Blaster");
        pidMap.put("3223", "HANDYGAMES Dreamjob: Kid's Doctor ");
        pidMap.put("3224", "HANDYGAMES Horse World 3D (Th");
        pidMap.put("3225", "HANDYGAMES Pixel Heroes: Bytes & Magic ");
        pidMap.put("3226", "HANDYGAMES The Inner World - The Puzzle ");
        pidMap.put("3227", "HANDYGAMES Wild Life Africa ");
        pidMap.put("3230", "HANDYGAMES Sci-Fighters ");
        pidMap.put("3066", "Nitro Street Run 2 ");
        pidMap.put("3235", "INLOGIC Baseball Pro 2017 ");
        pidMap.put("3236", "JOYBITS Splash Rush ");
        pidMap.put("3237", "JOYBITS Blast Mania ");
        pidMap.put("3238", "JOYBITS Triple Saga ");
        pidMap.put("3239", "BALTORO Bowling Fever ");
        pidMap.put("3243", "PLAYMOUS God of Light ");
        pidMap.put("3251", "INLOGIC Parking Madness ");
        pidMap.put("3253", "BALTORO Awesome Burger Bar ");
        pidMap.put("3255", "DOTEMU Double Dragon 2 ");
        pidMap.put("3256", "DOTEMU Double Dragon 3 ");
        pidMap.put("3257", "JOYBITS Doodle God: Fantasy World of Magic");
        pidMap.put("3258", "JOYBITS Doodle God: Rocket Scientist ");
        pidMap.put("3259", "GLOBALFUN El Che ");
        pidMap.put("3261", "DOTEMU R-Type ");
        pidMap.put("3261", "DOTEMU R-Type 2 ");
        pidMap.put("3262", "DOTEMU Raiden Legacy ");
        pidMap.put("3264", "BALTORO Awesome Sushi Bar ");
        pidMap.put("3268", "JOYBITS Alchemy Jam ");
        pidMap.put("3271", "JOYBITS The Great Unknown: Houdini's Castle");
        pidMap.put("3272", "INLOGIC Jelly Jewel ");
        pidMap.put("3273", "GLOBALFUN Road to Kill ");
        pidMap.put("3277", "JOYBITS The Surprising Adventures of Munchausen ");
        pidMap.put("3278", "INLOGIC Color Pin");
        pidMap.put("3279", "SHINYPIX Little Red Riding Hood ");
        pidMap.put("3287", "GLOBALFUN Zombie Rising ");
        pidMap.put("3290", "BALTORO Hooooop! ");
        pidMap.put("3291", "BALTORO Diamonds Bay Paradise ");
        pidMap.put("3293", "GLOBALFUN Formula Cartoon All-Stars ");
        pidMap.put("3295", "GLOBALFUN Gumball Racing ");
        pidMap.put("3303", "GLOBALFUN Tom & Jerry: Mouse Maze - Summer Edition ");
        pidMap.put("3304", "JOYBITS Chess ");
        pidMap.put("3308", "BALTORO Street Racing PRO ");
        pidMap.put("3310", "WHAT GAMES Boboiboy ");
        pidMap.put("3311", "BALTORO Real Drift Racing");
        pidMap.put("3312", "PLAYMOUS Dash Masters ");
        pidMap.put("3314", "INLOGIC Candy Thieves 3D ");
        pidMap.put("3315", "BALTORO Baseball World Trophy 2017 ");
        pidMap.put("3316", "GLOBALFUN Battleship Modern ");
        pidMap.put("3318", "HANDYGAMES Azkend 2 ");
        pidMap.put("3319", "HANDYGAMES Boulder Rush  ");
        pidMap.put("3321", "HANDYGAMES King Oddball ");
        pidMap.put("3322", "HANDYGAMES Meganoid 2017 ");
        pidMap.put("3323", "HANDYGAMES Sparkle 2 ");
        pidMap.put("3324", "HANDYGAMES Heroes of Loot 2 ");
        pidMap.put("3325", "INLOGIC Color Swap ");
        pidMap.put("3329", "BALTORO Airborne Grannies ");
        pidMap.put("3330", "INLOGIC Fidget Spinner ");
        pidMap.put("3333", "INLOGIC Pool Pro ");
        pidMap.put("3334", "INLOGIC 2in1 Ultimate Pack ");
        pidMap.put("3338", "HANDYGAMES Tennis in the Face ");
        pidMap.put("3339", "GLOBALFUN Ben 10 Ultimate Alien - Ultimate Defender ");
        pidMap.put("3340", "GLOBALFUN Subway Surfers ");
        pidMap.put("3341", "INLOGIC Bou ");
        pidMap.put("3343", "BALTORO Deadly Fighter 2");
        pidMap.put("3345", "INLOGIC Zoo Quiz ");
        pidMap.put("3346", "BALTORO 7 Cells! ");
        pidMap.put("3347", "BALTORO Diamond Hunt ");
        pidMap.put("3348", "PLAYMOUS Paint the Frog ");
        pidMap.put("3355", "HANDYGAMES Foosball Cup World ");
        pidMap.put("3381", "BALTORO Fishing Mania ");
        pidMap.put("3382", "INLOGIC Pro Tennis 2018 ");
        pidMap.put("3384", "BALTORO Motorbikes PRO 2017 ");
        pidMap.put("3386", "INLOGIC Pro Cricket 2018 ");
        pidMap.put("3389", "Gameloft Classics: Arcade ");
        pidMap.put("3401", "INLOGIC Zombie Rider");
        pidMap.put("3421", "JOYBITS Emma The Cat - Virtual Pet ");
        pidMap.put("3431", "JOYBITS My Talking Dog - Virtual Pet ");
        pidMap.put("3432", "INLOGIC 2in1 Car Games");
        pidMap.put("3433", "JOYBITS Galaxy Warfighter");
        pidMap.put("3434", "JOYBITS Gem Legends ");
        pidMap.put("3435", "JOYBITS Magic Cube Puzzle 3D ");
        pidMap.put("3436", "JOYBITS Real Retro Games 2 ");
        pidMap.put("3437", "JOYBITS Mind Games ");
        pidMap.put("3442", "BALTORO Crazy Birds Match ");
        pidMap.put("3443", "BALTORO Moto Racer Fury");
        pidMap.put("3444", "WHAT GAMES Little Big Tree");
        pidMap.put("3446", "BALTORO My Salad Bar ");
        pidMap.put("3450", "HANDYGAMES Stack The Balls ");
        pidMap.put("3451", "INLOGIC Street Racer Underground ");
        pidMap.put("3453", "GLOBALFUN Subway Surfers Halloween");
        pidMap.put("3454", "Gameloft Classics: Action ");
        pidMap.put("3318", "HANDYGAMES Azkend ");
        pidMap.put("3457", "HANDYGAMES Joining Hands ");
        pidMap.put("3323", "HANDYGAMES Sparkle");
        pidMap.put("3459", "HANDYGAMES Stop the Robots ");
        pidMap.put("3461", "HANDYGAMES Zombie Derby ");
        pidMap.put("3462", "INLOGIC Minigolf Mania ");
        pidMap.put("3468", "HANDYGAMES Jolly Days Farm ");
        pidMap.put("3470", "GLOBALFUN Scooby Doo - Shaggy & The Ghost Blocks ");
        pidMap.put("3471", "BALTORO Bubble Crush ");
        pidMap.put("3472", "BALTORO Headball Football");
        pidMap.put("3473", "GLOBALFUN Ski Safari: Adventure Time ");
        pidMap.put("3474", "INLOGIC snakes.io 2");
        pidMap.put("3475", "JOYBITS Escape from the Plateau ");
        pidMap.put("3477", "BALTORO Drag Boats Racing ");
        pidMap.put("3479", "JOYBITS Ice Crystal Adventure ");
        pidMap.put("3481", "INLOGIC Santa's Xmas Adventure ");
        pidMap.put("3494", "WHAT GAMES Cosmo Bounce ");
        pidMap.put("3497", "Rival Wheels");
        pidMap.put("3498", "INLOGIC Star Drives 2 ");
        pidMap.put("3506", "GLOBALFUN Vikings");
        pidMap.put("3507", "HANDYGAMES Baseball Riot");
        pidMap.put("3512", "INLOGIC Magic Forest Match ");
        pidMap.put("3514", "BALTORO Food Truck Tycoon ");
        pidMap.put("3515", "BALTORO Ultimate Truck Racing ");
        pidMap.put("3516", "INLOGIC Giga Jump 2 ");
        pidMap.put("3521", "GLOBALFUN Tom & Jerry: Mouse Maze - Christmas Edition ");
        pidMap.put("3522", "HANDYGAMES Ironworm ");
        pidMap.put("3523", "INLOGIC Temple Rush");
        pidMap.put("3527", "GLOBALFUN Ronaldo: Kick 'N' Run ");
        pidMap.put("3529", "BALTORO Street Bowling ");
        pidMap.put("3531", "INLOGIC Lucky Slots ");
        pidMap.put("3538", "BALTORO Pancake Chef ");
        pidMap.put("3539", "BALTORO Monster Truck Racing ");
        pidMap.put("3540", "BALTORO GoKarts Championships ");
        pidMap.put("3550", "INLOGIC Basketball Mania ");
        pidMap.put("3551", "BALTORO Sea Wolf Attack ");
        pidMap.put("3556", "BALTORO Quick Golf");
        pidMap.put("3562", "BALTORO Bubble Cats Rescue ");
        pidMap.put("3591", "Gameloft Classics: Shooters");
        pidMap.put("3602", "BALTORO Space Defender ");
        pidMap.put("3603", "GLOBALFUN We Bare Bears - Quest for Nom Nom");
        pidMap.put("3657", "BALTORO Pet Shop Snacks");
        pidMap.put("3664", "GLOBALFUN Agent Gumball ");
        pidMap.put("3673", "BALTORO Ludomania ");
        pidMap.put("3674", "GLOBALFUN Subway Surfers Chicago ");
        pidMap.put("3701", "GLOBALFUN Tom & Jerry: Mouse Maze - Deluxe ");
        pidMap.put("3702", "PLAYDIGIOUS Mini Metro ");
        pidMap.put("2616", "GLOBALFUN Tom & Jerry ");
        pidMap.put("2644", "GLOBALFUN Scooby Doo! Saving Shaggy ");
        pidMap.put("2674", "GLOBALFUN Adventure Time - Heroes of Ooo ");
        pidMap.put("2700", "GLOBALFUN Ben 10 Omniverse");

        //2nd times - 2019/04/19
        pidMap.put("199", "Real Football");
        pidMap.put("1894", "Real Football");

        //pidMap.put("1669", "2014 Real Football Mobile TnB");
        //pidMap.put("1843", "2015 Real Football Mobile Premium");
        //pidMap.put("2617", "2017 Real Football Mobile Freemium");
        pidMap.put("2755", "Air Strike 1944");
        //pidMap.put("77", "AND 1 Streetball");
        pidMap.put("2179", "BALTORO Extreme Quad Bikes Pro");
        pidMap.put("2629", "BALTORO Go Kart Mania 2 MRE");
        pidMap.put("1113", "Block Breaker");
        pidMap.put("1413", "Block Breaker Deluxe");
        //pidMap.put("2754", "Block Breaker Native TnB");
        //pidMap.put("508", "Camera Café");
        //pidMap.put("151", "Christmas Midnight Pool ");
        //pidMap.put("3231", "Danger Dash HTML5");
        //pidMap.put("2033", "Disney Magic Kingdoms Mobile Freemium");
        //pidMap.put("2952", "Dungeon Hunter Curse of Heaven Mobile Premium");
        //pidMap.put("771", "Ferrari World Championship 2009");
        //pidMap.put("742", "HAWX");
        //pidMap.put("1753", "INLOGIC Dragon Run");
        //pidMap.put("2623", "INLOGIC Jewel Craft");
        //pidMap.put("1568", "INLOGIC Jewel Craft");
        //pidMap.put("2757", "INLOGIC Polar Pong");
        //pidMap.put("2763", "INLOGIC Sir Yes Sir");
        //pidMap.put("2252", "INLOGIC Tower Mania");
        //pidMap.put("2046", "INLOGIC Tubby Birds");
        //pidMap.put("3220", "TETRIS Mobile TnB");
        //pidMap.put("1764", "Spiderman Ultimate Power Mobile Freemium ");
        //pidMap.put("7", "Siberian Strike");
        //pidMap.put("2718", "Real Football Runner HTML5");
        //pidMap.put("1669", "Real Football Mobile Premium");
        //pidMap.put("1379", "Puzzle Pets Mobile Freemium");
        //pidMap.put("2842", "Puzzle Pets Memory HTML5");
        //pidMap.put("2771", "Pastry Paradise HTML5");
        //pidMap.put("2812", "NitroStreet: DragMode HTML5");
        //pidMap.put("2753", "Nitro Racing Native TnB");
        //pidMap.put("2186", "Nitro Racing Native TnB");
        //pidMap.put("1045", "N.O.V.A. HD+");
        //pidMap.put("982", "March of Heroes");

    }
}
